# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AtlasGeoHandlerDemo
                                 A QGIS plugin
 QGIS integrated plugin for UAV Pose Estimation and UAV-to-Map Registration
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-20
        git sha              : $Format:%H$
        copyright            : © 2026 AIVE AI Systems
        email                : luis.sentis@aivesystems.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):  # pylint: disable=unused-argument
    """Load AtlasGeoHandlerDemo class from file atlas_geo_plugin.
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .atlas_geo_plugin import AtlasGeoHandlerDemo
    return AtlasGeoHandlerDemo(iface)
