# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Resources for ATLAS Geo-Dock Plugin
 Generated from resources.qrc
 ***************************************************************************/

# Resource object code (Python 3)

# This file is automatically generated - do not edit
# Use: pyrcc5 resources.qrc -o resources.py

"""

import sys

qt_resource_data = b""

qt_resource_name = b""

qt_resource_struct = b""


def qInitResources():
    """Initialize resource system"""
    pass


def qCleanupResources():
    """Cleanup resource system"""
    pass


if __name__ == '__main__':
    qInitResources()
